name: TestGitHub_Action
on:  push


jobs:  
  testJob:
    runs-on: ubuntu-latest


    steps:
    - name: print test
      run:  echo "print Test"

    - name: Display file content
      run: test.txt
        
