name: TestGitHub_Action
on:
  push

jobs:  
  testJob:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Display file content
        run: cat test.txt


      - name: Checkout code
        uses: action/checkout@v4
        with:
          repository:  MathanRasu/Terrafrom_AWS
          token: ${{ secrets.TOKEN_VALUE }}
          path: variables.tf
          run: cat variables.tf
