name: TestGitHub_Action
on:
  push

jobs:  
  testJob:
    runs-on: ubuntu-latest

    steps: 
      # Step 1: Checkout the current repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Checkout another repository
      - name: Checkout another repository
        uses: actions/checkout@v4
        with:
          repository: MathanRasu/Terrafrom_AWS 
          token: ${{ secrets.TOKEN_TEST }}    
          path: other-repo                    

      # Step 3: Display the file content
      - name: Display file content
        run: cat other-repo/variables.tf      
